BEGIN;
UPDATE product_image pi SET origin_image = 'catalog/custom/bal-001_chicken-veggie.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'BAL-001');
UPDATE product_image pi SET origin_image = 'catalog/custom/bal-002_salmon-brown-rice.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'BAL-002');
UPDATE product_image pi SET origin_image = 'catalog/custom/bal-003_veggie-delight.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'BAL-003');
UPDATE product_image pi SET origin_image = 'catalog/custom/bal-004_tuna-wholegrain.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'BAL-004');
UPDATE product_image pi SET origin_image = 'catalog/custom/bal-005_beef-and-veg.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'BAL-005');
UPDATE product_image pi SET origin_image = 'catalog/custom/bal-006_egg-and-avocado.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'BAL-006');
UPDATE product_image pi SET origin_image = 'catalog/custom/bal-007_shrimp-quinoa.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'BAL-007');
UPDATE product_image pi SET origin_image = 'catalog/custom/bal-008_family-bento.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'BAL-008');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-001_grilled-chicken-quinoa.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-001');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-002_tuna-avocado-salad.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-002');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-003_tofu-veggie-protein.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-003');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-004_turkey-brown-rice.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-004');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-005_shrimp-zucchini-noodle.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-005');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-006_lean-beef-broccoli.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-006');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-007_egg-white-breakfast.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-007');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-008_salmon-greens.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-008');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-009_chicken-teriyaki-lite.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-009');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-010_mediterranean-chickpea.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-010');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-011_yogurt-berry-fit.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-011');
UPDATE product_image pi SET origin_image = 'catalog/custom/flb-012_low-carb-bento.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'FLB-012');
UPDATE product_image pi SET origin_image = 'catalog/custom/mgb-001_double-chicken-rice.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'MGB-001');
UPDATE product_image pi SET origin_image = 'catalog/custom/mgb-002_beef-steak-power.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'MGB-002');
UPDATE product_image pi SET origin_image = 'catalog/custom/mgb-003_salmon-sweet-potato.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'MGB-003');
UPDATE product_image pi SET origin_image = 'catalog/custom/mgb-004_turkey-pasta-protein.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'MGB-004');
UPDATE product_image pi SET origin_image = 'catalog/custom/mgb-005_peanut-butter-oat.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'MGB-005');
UPDATE product_image pi SET origin_image = 'catalog/custom/mgb-006_tuna-rice-power.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'MGB-006');
UPDATE product_image pi SET origin_image = 'catalog/custom/mgb-007_tofu-tempeh-gain.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'MGB-007');
UPDATE product_image pi SET origin_image = 'catalog/custom/mgb-008_greek-yogurt-granola.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'MGB-008');
UPDATE product_image pi SET origin_image = 'catalog/custom/mgb-009_chicken-avocado.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'MGB-009');
UPDATE product_image pi SET origin_image = 'catalog/custom/mgb-010_high-protein-bento.jpg' WHERE pi.product_image_product_id = (SELECT product_id FROM product WHERE sku = 'MGB-010');
UPDATE product_image SET origin_image = CONCAT('/assets/', origin_image) WHERE origin_image LIKE 'catalog/custom/%';
COMMIT;
